added command line args to set verbose option

diff --git a/create_rpm b/create_rpm
--- a/create_rpm
+++ b/create_rpm
@@ -17,6 +17,35 @@
 #
 curdir=`pwd`
 version=$(cat conf-version)
+
+if [ -f /etc/debian_version ] ; then
+	echo "you can't do rpmbuild on an insane system" 1>&2
+	exit 1
+fi
+
+verbose=0
+while test $# -gt 0; do
+    case "$1" in
+    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'`
+	;;
+    *) optarg=
+	;;
+    esac
+
+    case "$1" in
+    --verbose)
+	verbose=1
+    ;;
+    *)
+    echo "invalid option [$1]"
+    read key
+    usage 1
+    ;;
+    esac
+
+    shift
+done
+
 cd ..
 /bin/rm -rf /tmp/libqmail-"$version"
 cp -rp libqmail /tmp/libqmail-"$version"
@@ -83,25 +112,34 @@ if [ " $key" = " Y" -o " $key" = " y" ] ; then
 			cd ..
 		fi
 	fi
-	echo "rpmbuild -ba --clean --quiet /tmp/libqmail.spec"
-	rpmbuild -ba --clean --quiet /tmp/libqmail.spec
-	/bin/rm /tmp/libqmail.spec
-	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
-	rpm --addsign $rpmbuild/RPMS/$build_arch/libqmail-"$version"-"1.$release".$dist.$build_arch.rpm
-	echo -n "RPM lint for libqmail-"$version"-1."$release" (Y/N) - "
-	read key
-	if [ " $key" = " Y" -o " $key" = " y" ] ; then
-		(
-		echo libqmail
-		rpmlint $rpmbuild/RPMS/$build_arch/libqmail-"$version"-"1.$release".$dist.$build_arch.rpm
-		echo ------------------------
-		echo libqmail-devel
-		rpmlint $rpmbuild/RPMS/$build_arch/libqmail-devel-"$version"-"1.$release".$dist.$build_arch.rpm
-		echo ------------------------
-		echo libqmail-"$version"-"1.$release".$dist.src.rpm
-		rpmlint $rpmbuild/SRPMS/libqmail-"$version"-"1.$release".$dist.src.rpm
-		echo ------------------------
-		) 2>&1 | less
+	if [ $verbose -eq 0 ] ; then
+		echo "rpmbuild -ba --clean --quiet /tmp/libqmail.spec"
+		rpmbuild -ba --clean --quiet /tmp/libqmail.spec
+	else
+		echo "rpmbuild -ba --clean /tmp/libqmail.spec"
+		rpmbuild -ba --clean /tmp/libqmail.spec
+	fi
+	if [ $? -eq 0 ] ; then
+		/bin/rm /tmp/libqmail.spec
+		build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
+		rpm --addsign $rpmbuild/RPMS/$build_arch/libqmail-"$version"-"1.$release".$dist.$build_arch.rpm
+		echo -n "RPM lint for libqmail-"$version"-1."$release" (Y/N) - "
+		read key
+		if [ " $key" = " Y" -o " $key" = " y" ] ; then
+			(
+			echo libqmail
+			rpmlint $rpmbuild/RPMS/$build_arch/libqmail-"$version"-"1.$release".$dist.$build_arch.rpm
+			echo ------------------------
+			echo libqmail-devel
+			rpmlint $rpmbuild/RPMS/$build_arch/libqmail-devel-"$version"-"1.$release".$dist.$build_arch.rpm
+			echo ------------------------
+			echo libqmail-"$version"-"1.$release".$dist.src.rpm
+			rpmlint $rpmbuild/SRPMS/libqmail-"$version"-"1.$release".$dist.src.rpm
+			echo ------------------------
+			) 2>&1 | less
+		fi
+	else
+		/bin/rm /tmp/libqmail.spec
 	fi
 else
 	/bin/rm -rf /tmp/libqmail-"$version"
